// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCGRMlwSsPgslQrbgkd5QDWQtI22v0H8U',
    appId: '1:487495695448:web:8030c2ee9c47d083165e2d',
    messagingSenderId: '487495695448',
    projectId: 'iot-framework-af56f',
    authDomain: 'iot-framework-af56f.firebaseapp.com',
    storageBucket: 'iot-framework-af56f.firebasestorage.app',
    measurementId: 'G-KFMJ150XH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKfpNI9mhv87xpFcANFW1KMcSUpMgi9go',
    appId: '1:487495695448:android:a4fd81f39633b28e165e2d',
    messagingSenderId: '487495695448',
    projectId: 'iot-framework-af56f',
    storageBucket: 'iot-framework-af56f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKBVOspGjYfJ6NjCK0SiwGWXIyCoAQWXg',
    appId: '1:487495695448:ios:28586da1669963aa165e2d',
    messagingSenderId: '487495695448',
    projectId: 'iot-framework-af56f',
    storageBucket: 'iot-framework-af56f.firebasestorage.app',
    iosBundleId: 'com.example.iotframework',
  );
}
